message("-- Selecting compiler Ops...")

# Define common compiler flags
set(CMAKE_C_FLAGS "")
set(CMAKE_C_FLAGS_DEBUG "-g -O0")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS "")
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")
set(CMAKE_Fortran_FLAGS "")
set(CMAKE_Fortran_FLAGS_DEBUG "-g -O0")
set(CMAKE_Fortran_FLAGS_RELEASE "-O3")

# Define specific flags
if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
	message("-- GNU compiler detected")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Intel")
	message("-- Intel compiler detected")
elseif(CMAKE_C_COMPILER_ID STREQUAL "NVHPC")
	message("-- NVHPC compiler detected")
	set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -lnvToolsExt -Minfo=accel")
	set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -lnvToolsExt -Minfo=accel")
	set(CMAKE_Fortran_FLAGS ${CMAKE_Fortran_FLAGS} "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -lnvToolsExt -Minfo=accel")
	if(USE_GPU AND USE_MEM_MANAGED)
		message("Setting up ACC flags with managed memory")
	elseif(USE_GPU)
		message("Setting up ACC flags")
	endif()
else()
	message(FATAL_ERROR "Unknown compiler")
endif()

if(USE_PCPOWER)
  include(powerpcCompilers)
elseif(USE_MN)
  include(marenostrumCompilers)
else()
  include(localCompilers)
endif()

set(CMAKE_C_FLAGS "")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g3")
set(CMAKE_C_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS "")
set(CMAKE_CXX_FLAGS_DEBUG "-O0")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")

if(USE_GPU)
  message(" # Using GPUs...")
  if((NOT USE_PCPOWER) AND (NOT USE_MN))
    include_directories("/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/include/")
  endif()
  #add_link_options(-lnvToolsExt)
  if(USE_MEM_MANAGED)
    message(" # Using GPU Flags with Memory Managed Option...")
    set(CMAKE_Fortran_FLAGS         "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,managed,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
    set(CMAKE_Fortran_FLAGS_RELEASE "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,managed,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
    set(CMAKE_Fortran_FLAGS_DEBUG   "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,managed,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
  else()
    message(" # Using GPU Flags WITHOUT Memory Managed Option...")
    set(CMAKE_Fortran_FLAGS         "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
    set(CMAKE_Fortran_FLAGS_RELEASE "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
    set(CMAKE_Fortran_FLAGS_DEBUG   "-cpp -lstdc++ -lmpi_cxx -DNOPRED -fast -D_USE_NVTX -gpu=cc70,lineinfo -cuda -acc -lnvToolsExt -Minfo=accel")
  endif()
else()
  message(" # NOT Using GPUs...")
  if(USE_MN)
    message(" # Using MN Compiler Flags...")
    set(CMAKE_Fortran_FLAGS         "-cpp -lstdc++  -DNOPRED -DNOACC -O3 -xCORE-AVX512 -mtune=skylake")
    set(CMAKE_Fortran_FLAGS_RELEASE "-cpp -lstdc++  -DNOPRED -DNOACC -O3 -xCORE-AVX512 -mtune=skylake")
    set(CMAKE_Fortran_FLAGS_DEBUG   "-cpp -lstdc++  -DNOPRED -DNOACC -O3 -xCORE-AVX512 -mtune=skylake")
  else()
    message(" # Using Local Machine Compiler Flags...")
    set(CMAKE_Fortran_FLAGS         "-cpp -lstdc++ -ffree-line-length-512 -DNOPRED -DNOACC -O3")
    set(CMAKE_Fortran_FLAGS_RELEASE "-cpp -lstdc++ -ffree-line-length-512 -DNOPRED -DNOACC -O3")
    set(CMAKE_Fortran_FLAGS_DEBUG   "-cpp -lstdc++ -ffree-line-length-512 -DNOPRED -DNOACC -O3")
  endif()
endif()
