function(set_gempa)
  if (USE_GEMPA)
    include_directories(${GEMPA_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} gempa)
  else()
    message("  -- Not using GEMPA...")
    add_definitions(-DNO_SFC)
  endif()
endfunction()
