message("-- Compiling in Local Machine. Using compilers defined in cmake/localCompilers.cmake")
if (USE_MPI)
   message(" # Using MPI compiler wrappers...")
   set(CMAKE_C_COMPILER       "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/comm_libs/mpi/bin/mpicc")
   set(CMAKE_CXX_COMPILER     "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/comm_libs/mpi/bin/mpicxx")
   set(CMAKE_Fortran_COMPILER "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/comm_libs/mpi/bin/mpif90")
else()
   message(" # Using NV compiler wrappers...")
   set(CMAKE_C_COMPILER       "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvc")
   set(CMAKE_CXX_COMPILER     "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvc++")
   set(CMAKE_Fortran_COMPILER "/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvfortran")
endif()