message("-- Compiling in PCPOWER...")
if (USE_MPI)
  message(" # Using MPI compiler wrappers...")
  set(CMAKE_C_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/comm_libs/mpi/bin/mpicc")
  set(CMAKE_CXX_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/comm_libs/mpi/bin/mpic++")
  set(CMAKE_Fortran_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/comm_libs/mpi/bin/mpif90")
else()
  message(" # Using NV compiler wrappers...")
  set(CMAKE_C_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/compilers/bin/nvc")
  set(CMAKE_CXX_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/compilers/bin/nvc++")
  set(CMAKE_Fortran_COMPILER "/apps/NVIDIA-HPC-SDK/22.2/Linux_ppc64le/22.2/compilers/bin/nvfortran")
endif()