message("-- Configuring SENSEI, if appropriate...")
if (USE_SENSEI)
	#  message("-- In case you need it, set your SENSEI_ROOT here:")
	#  set(SENSEI_ROOT "/your_local_path_to_sensei_lib/")
	if(DEFINED ENV{SENSEI_ROOT})
	  message("-- SENSEI_ROOT properly set in environmental var:" $ENV{SENSEI_ROOT})
	elseif(DEFINED ENV{SENSEI_DIR})
	  message("-- SENSEI_DIR properly set in environmental var:" $ENV{SENSEI_DIR})
	elseif(SENSEI_ROOT)
	  message("-- SENSEI_ROOT properly set in cmake:" ${SENSEI_ROOT})
	else()
	  message("-- POSSIBLE ERROR! Environmental variables SENSEI_ROOT/SENSEI_DIR not properly set!")
	  message("-- If Cmake does not find SENSEI package you have two options:")
	  message("--   1. Define environmental variables SENSEI_ROOT and/or SENSEI_DIR")
	  message("--   2. In case you don't wnow ant/can't, define SENSEI_ROOT in cmake/sensei.cmake")
	  message("-- If Cmake find SENSEI everything is Ok!")
	endif()
	find_package(SENSEI REQUIRED)
	find_file(SENSEI_CONFIG_FILE DOC "config for SENSEI's configuarable analysis adaptor" REQUIRED)
	target_compile_definitions(${PROJECT_NAME} PRIVATE SENSEI_CONFIG_FILE="${SENSEI_CONFIG_FILE}")
endif()

function(set_sensei)
	include_directories(${SENSEI_INCLUDE_DIRS})
	target_link_libraries(${PROJECT_NAME} sensei)
endfunction()
